/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISnaptureNFT } from "./ISnaptureNFT";
export type { ISnaptureWorkflow } from "./ISnaptureWorkflow";
