/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { INft, INftInterface } from "../../contracts/INft";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "projectId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "jobId",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "tokenUri",
        type: "string",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class INft__factory {
  static readonly abi = _abi;
  static createInterface(): INftInterface {
    return new Interface(_abi) as INftInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): INft {
    return new Contract(address, _abi, runner) as unknown as INft;
  }
}
