/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ISnaptureNFT__factory } from "./ISnaptureNFT__factory";
export { ISnaptureWorkflow__factory } from "./ISnaptureWorkflow__factory";
