/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISnaptureNFT,
  ISnaptureNFTInterface,
} from "../../../contracts/interfaces/ISnaptureNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "string",
        name: "tokenUri",
        type: "string",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISnaptureNFT__factory {
  static readonly abi = _abi;
  static createInterface(): ISnaptureNFTInterface {
    return new Interface(_abi) as ISnaptureNFTInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISnaptureNFT {
    return new Contract(address, _abi, runner) as unknown as ISnaptureNFT;
  }
}
